name: "Build and Deploy"
on:
  release:
    types: [published,edited]
jobs:
  build:
    # Set up the OS
    runs-on: ubuntu-latest
    env:
      # Nexus credentials and GitHub token
      NEXUS_USERNAME: '${{ secrets.NEXUS_USERNAME }}'
      NEXUS_PASSWORD: '${{ secrets.NEXUS_PASSWORD }}'
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      # Set environment
      env: 'prod'
    steps:
      # Checkout the Code
      - name: Checkout Code
        uses: actions/checkout@v2
      # Set up git hashes environment variables
      - name: Git Hashes
        uses: Im-Fran/git-hashes-action@v1.0.0
        # Set up version from tag environment variables
      - name: Version from Tag Action
        uses: Im-Fran/version-from-tag-action@v1.0.1
        with:
          remove-first-character: 'v'
        # Set up the JDK
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
      # Validate Gradle Wrapper
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      # Make gradle executable
      - name: Make gradle executable
        run: chmod +x gradlew
      # Clean, Test, Publish and Build (in that order to save the artifact to the action)
      - name: Test, Deploy and Build with Gradle
        run: ./gradlew clean test publish shadow
      # Now we store the artifact in the action
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: SuperCoreAPI
          path: ./build/libs/SuperCoreAPI.jar
      # Now we deploy the documents to GitHub pages
      - name: Deploy Javadoc
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: build/docs/javadoc
          clean: true
