name: Java CI
on:
  release:
    types: [published,prereleased]
jobs:
  build:
    # Setup the OS
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 
    env:
      NEXUS_USERNAME: '${{ secrets.NEXUS_USERNAME }}'
      NEXUS_PASSWORD: '${{ secrets.NEXUS_PASSWORD }}'
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    steps:
    # Checkout the code
    - name: Ceckout the Code
      uses: actions/checkout@v2
    # Install java and maven
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
    # Validate Gradle Wrapper
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    # Test and deploy
    - name: Make gradle executable
      run: chmod +x gradlew
    - name: Test and Deploy with Gradle
      run: ./gradlew clean test shadow publish
      # Now we store the artifact in the action
    - name: Create & Copy artifact
      run: mkdir -p ./artifacts && cp build/libs/SuperCoreAPI.jar ./artifacts/
    - name: Upload the artifact
      uses: actions/upload-artifact@v2
      with:
        name: SuperCoreAPI
        path: ./artifacts/SuperCoreAPI.jar
    - name: Deploy Javadoc
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: build/docs/javadoc
        clean: true
      
      
